repos:
  - repo: local
    hooks:
      - id: format
        name: format Rust files
        entry: cargo fmt -- --files-with-diff
        language: system
        types: [rust]
        priority: 1

      - id: clippy
        name: lint Rust files
        entry: cargo clippy --fix --allow-dirty -- -D warnings
        language: system
        pass_filenames: false
        types: [rust]
        priority: 2

      - id: test
        name: test Rust code
        entry: cargo test
        language: system
        pass_filenames: false
        types: [rust]
        priority: 100

      - id: mdlint
        name: check Markdown files
        entry: cargo run --
        language: system
        types_or: [markdown]
        priority: 1

      - id: hadolint
        name: check Docker files
        entry: mise exec -- hadolint
        language: system
        files: Dockerfile$
        priority: 1

  - repo: builtin
    hooks:
      - id: check-toml
        priority: 1
      - id: check-yaml
        priority: 1
      - id: trailing-whitespace
        priority: 1

