fail_fast = true

[[repos]]
repo = "builtin"

[[repos.hooks]]
id = "trailing-whitespace"

[[repos.hooks]]
id = "check-yaml"

[[repos]]
repo = "local"

[[repos.hooks]]
id = "tombi-fmt"
name = "format TOML"
entry = "tombi format"
language = "system"
pass_filenames = false
types = ["toml"]
priority = 1

[[repos.hooks]]
id = "tombi-check"
name = "check TOML"
entry = "tombi check"
language = "system"
pass_filenames = false
types = ["toml"]
priority = 2

[[repos.hooks]]
id = "rustfmt"
name = "format Rust"
entry = "cargo fmt -- --files-with-diff"
language = "system"
pass_filenames = false
types = ["rust"]
priority = 2

[[repos.hooks]]
id = "clippy"
name = "clippy"
entry = "cargo clippy --fix --allow-dirty --all-targets --all-features -- -D warnings"
language = "system"
pass_filenames = false
types = ["rust"]
priority = 3

[[repos.hooks]]
id = "test"
name = "test Rust"
entry = "cargo test"
language = "system"
pass_filenames = false
types = ["rust"]
priority = 4

[[repos.hooks]]
id = "mdlint"
name = "check Markdown (dogfood)"
entry = "cargo run -- check --exclude FORMAT_SPEC.md"
language = "system"
pass_filenames = false
types = ["rust"]
priority = 5

[[repos.hooks]]
id = "hadolint"
name = "check Dockerfile"
entry = "hadolint"
language = "system"
files = "^Dockerfile$"
priority = 1
