name: npm

on:
  workflow_call:

jobs:
  publish:
    name: Publish npm package
    runs-on: ubuntu-latest
    environment: npm
    permissions:
      contents: read
      id-token: write # OIDC trusted publishing
    defaults:
      run:
        working-directory: npm
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7
        with:
          sparse-checkout: npm

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020  # v7
        with:
          node-version: 'lts/*'

      - name: Upgrade npm
        run: npm install -g npm@latest

      - name: Download binaries
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          pattern: mdlint-*
          path: /tmp/binaries
          merge-multiple: true

      - name: Stage binaries
        working-directory: npm/bin
        run: |
          mv /tmp/binaries/mdlint-linux-x86_64       mdlint-linux-x64
          mv /tmp/binaries/mdlint-linux-x86_64-musl  mdlint-linux-x64-musl
          mv /tmp/binaries/mdlint-linux-aarch64      mdlint-linux-arm64
          mv /tmp/binaries/mdlint-linux-aarch64-musl mdlint-linux-arm64-musl
          mv /tmp/binaries/mdlint-macos-x86_64       mdlint-darwin-x64
          mv /tmp/binaries/mdlint-macos-aarch64      mdlint-darwin-arm64
          mv /tmp/binaries/mdlint-windows-x86_64.exe mdlint-win32-x64.exe
          chmod +x mdlint-*

      - name: Publish to npm
        run: npm publish --access public --provenance
